import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Keitumetse Modipa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="styles.container">
        <div>
          <h1>Testing</h1>
        </div>
      </main>
    </div>
  );
}
